server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: coupon-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: coupon-logs
          __path__: /var/logs/**/*.json.log

    pipeline_stages:
      - regex:
          expression: '/var/logs/(?P<app_name>[^/]+)/.*'
      - labels:
          app: app_name
      - json:
          expressions:
            level: level
            globalTraceId: globalTraceId
            traceId: traceId
            spanId: spanId
      - labels:
          level:
          globalTraceId:
          traceId:
          spanId: