server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://<모니터링_서버_Private_IP>:3100/loki/api/v1/push

scrape_configs:
  - job_name: coupon-system
    static_configs:
      - targets:
          - localhost
        labels:
          job: coupon-logs
          app: {애플리케이션_서버_로그_폴더명} # e.g. coupon-api, coupon-consumer
          __path__: /var/logs/*.json.log

    pipeline_stages:
      - json:
          expressions:
            level: level
            globalTraceId: globalTraceId
            traceId: traceId
            spanId: spanId
      - labels:
          level:
          globalTraceId:
          traceId:
          spanId: