spring:
  datasource:
    url: jdbc:mysql://localhost:3306/couponDB
    username: root
    password: 1234
  jpa:
    open-in-view: false # OSIV 기능을 비활성화합니다.
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  # sprig boot 3.x
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
    listener:
      ack-mode: manual

radisson:
  rate-limiter:
    coupon-issue:
      tps: 100

kafka:
  topic:
    coupon-issue: coupon_issue
    coupon-issue-retry: coupon_issue_retry
