spring:
  datasource:
    url: jdbc:mysql://localhost:3306/couponDB
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9093
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093

redisson:
  rate-limiter:
    coupon-issue:
      tps: 300

kafka:
  topic:
    coupon-issue: coupon_issue
    coupon-issue-retry: coupon_issue_retry

sentry:
  dsn: ${SENTRY_DSN}
